### ISSUE TITLE
Supermann is sending FQDN to riemann when the collectd config is false

### ISSUE THREAD

**Issue by ogg1e** [borntyping/supermann#12]
When I have this in my collectd.conf file:

Hostname    "intmessage01"
FQDNLookup   false

I'm still seeing it as com.company.intmessage01 when it gets to Riemann. It should be just intmessage01 when it gets to riemann. 

Other things being sent by collectd are fine and don't send the FQDN.

It seems to be picking up the value in /etc/hostname even if we set the FQDN lookup to false.

**Comment by borntyping** [comment]
Supermann and collectd are completely separate pieces of software. I'm not sure what you were expecting.

**Comment by ogg1e** [comment]
I just assumed that since it was being started by collectd that it would pick those settings up.

**Comment by borntyping** [comment]
This is specific to your infrastructure, sorry.

Supermann should be started by Supervisord, and I'm unaware of any other use cases.
